name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for raising an issue @${{ github.actor }}! Ritika will look into them as soon as possible :)'
        pr-message: '... and it seems to be your first PR here @${{ github.actor }}! We are happy to have you on board. :)'
